site_name: Python Project Johannes

docs_dir: docs

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          paths: [ src ]
  - render_swagger:
      title: API Reference

nav: [ ]

repo_url: https://github.com/johschmidt42/python-project-johannes

# to navigate with `/site` content correctly
use_directory_urls: false
