site_name: Python Project Johannes

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]

nav:
  - Index Page: index.md
  - Tutorials: tutorials.md
  - How-To-Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md

# to navigate with `/site` content correctly
use_directory_urls: false
