---
name: Build & Push

on:
#  release:
#    types: [published]
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # build
      - name: Build docker
        run: |
          set -o pipefail
          echo "TODO"
      # login to container registry
      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # build & push
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.repository }}/latest
          target: production
          github-token: ${{ github.token }}
