---
name: Build & Push

on:
#  release:
#    types: [published]
  push:
    branches:
      - feat/docker

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      # login to container registry
      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{version}}
      - name: Print docker meta
        run: |
          set -o pipefail
          echo "${{ steps.meta.outputs.tags }}"
          echo "${{ steps.meta.outputs.version }}"
          echo "${{ steps.meta.outputs.json }}"


#      # build & push
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: ghcr.io/${{ github.repository }}:latest
#          labels: |
#            org.opencontainers.image.source=https://github.com/johschmidt42/python-project-johannes
#            org.opencontainers.image.title=PYTHON_PROJECT_JOHANNES
##            org.opencontainers.image.version=
#          target: production
#          github-token: ${{ secrets.GH_TOKEN }}
