---
name: Documentation

on:
  release:
    types: [published]

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.3.1
      # set-up python with cache
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      # install requirements (including dev dependencies)
      - name: Install requirements
        run: poetry install --with docs
        # Create the openapi.json from the app
      - name: Create openapi.json
        run: |
         set -o pipefail
         poetry run make create_openapi
      # build & deploy docs
      - name: Build docs
        run: |
          set -o pipefail
          poetry run make docs-deploy
